### PR TITLE
[1.8] fix cluster early warm up

### PR DESCRIPTION
**Pull request by lambdai**
Description:
    cherry-pick below PRs from envoy upstream
    cluster manager: avoid immediate activation for dynamic inserted cluster when initialize (#12783)
    cluster: unstuck cluster manager when update the initializing cluster (#13875)

Risk Level: LOW
Testing: 
Docs Changes:
Release Notes:

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@lizan fyi

**Review by bianpengyuan — APPROVED** [review]

**Comment by lambdai** [comment]
@istio/release-managers-1-8

**Comment by lambdai** [comment]
Is it a github outrage that I cannot assign release-managers-1.8?

**Comment by lambdai** [comment]
^^ I gave up on assign the correct group since @bianpengyuan already approved.

Thanks!

**Pull request merged**
