### PR TITLE
[release-1.4] Fix create initial metadata 

### PR DESCRIPTION
**Pull request by bianpengyuan**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

ref: https://github.com/envoyproxy/envoy-wasm/issues/414

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@istio/release-managers-1-4 ptal, thanks.

**Comment by howardjohn** [comment]
Is this a backport?

**Comment by bianpengyuan** [comment]
Yes 1.5 pr: https://github.com/istio/envoy/pull/158.

master pr is blocked since it will need some clean up in ABI which is different from this fix: https://github.com/envoyproxy/envoy-wasm/pull/417

**Comment by mandarjog** [comment]
@bianpengyuan do we need to fix this in oss?

**Comment by bianpengyuan** [comment]
@mandarjog You mean whether we need to fix it in 1.4? I think for sure we need to fix it in oss. this is a bug, Create Initial Metadata callback never really works.

**Pull request closed without merging**
