### PR TITLE
[release-1.7] sync envoy-wasm

### PR DESCRIPTION
**Pull request by lambdai**
Including PRs from envoy-wasm

* Add Connection ID as property token 
* Update validation in Inline DNS table
* build: make emscripten stable

### CODE REVIEW

**Comment by lambdai** [comment]
CC @ericvn

**Comment by lambdai** [comment]
@lizan 
@gargnupur 

Do you need your individual PRs to release-1.7?

[ ] @lizan 
[ ] @gargnupur

**Comment by gargnupur** [comment]
@lambdai : Yes,  I need my PR, but I thought @bianpengyuan  already started porting it...https://github.com/istio/envoy/pull/240

**Comment by jwendell** [comment]
Be aware that [asan] tests are failing: https://github.com/istio/istio/issues/25752

**Comment by lambdai** [comment]
@gargnupur It should be merged successfully

**Comment by jwendell** [comment]
@lambdai note that currently our istio/envoy `release-1.7` branch is based on `release/v1.15` branch of envoyproxy/envoy-wasm.

I've noticed that the commits in this PR come from master.

Is this right? Shouldn't we pick up commits from `release/v1.15` instead? This branch is staled, by the way. No new commits on it. I'm guessing this is on purpose? 

So, our `release-1.7` branch is a mix of upstream `release/v1.15` plus selected commits from master? Please educate me.

**Comment by jwendell** [comment]
@rshriram please advice here as well. Are you expecting that our release-1.7 branch contains the commits in this PR?

What exactly did you mean when you said in the slack channel "release branch isn’t using the envoy release"? Are you expecting the release-1.7 branch contains commits from envoy-wasm master that are not in our base `release/v1.15`?

Context: Failures on https://github.com/istio/istio/pull/25795

**Comment by lambdai** [comment]
@jwendell 
Our goal is to make istio/envoy:release-1.7 close to envoyproxy/envoy:v.1.15 branch as close as possible but there is no hard rule.
That says,
1. we don't have to cherry-pick the exact commit SHA although it is preferred. Code equivalent is good enough.. 
2. If istio does have an extra work on top of envoyproxy release/v1.15, release manager should approve.

I believe DNS patch should be in.

**Comment by rshriram** [comment]
@jwendell @lambdai is right.. the code he has picked is equivalent (dns validation went into both branches IIRC).

**Review by jwendell — APPROVED** [review]

**Pull request merged**
