### PR TITLE
[release-1.6] manual cherry-pick of https://github.com/envoyproxy/env…

### PR DESCRIPTION
**Pull request by kyessenov**
…oy-wasm/pull/482

Signed-off-by: Kuat Yessenov <kuat@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by kyessenov** [comment]
@howardjohn can you use superpowers to merge this? It's a cherry-pick.

**Comment by howardjohn** [comment]
Why are we cherrypicking to master instead of just syncing up to head of envoy?

**Comment by kyessenov** [comment]
Envoy head and envoy-wasm diverged. Wasm changes do not automatically get merged.

**Comment by kyessenov** [comment]
See previous discussion. proxy-wasm is a breaking change in envoy-wasm and we chose to use pre-proxy-wasm for 1.6.

**Comment by howardjohn** [comment]
Thanks!

**Pull request merged**
