### PR TITLE
Backport listener in place update

### PR DESCRIPTION
**Pull request by lambdai**
Description:
Expect fewer connections be drained during listener update. 
The two major PRs are 
https://github.com/envoyproxy/envoy/pull/10662 and https://github.com/envoyproxy/envoy/pull/10528

Original commits:
c86c679dabe6813d779f32e0225abcd83a56b32f
and
ce5953b3fac3dfc5eed32be89d60fb1cd8fbf20d
 
Risk Level:
Testing:
Docs Changes:
Release Notes:
Envoy side of https://github.com/istio/istio/issues/22217

### CODE REVIEW

**Comment by lambdai** [comment]
@istio/release-managers-1-6

**Comment by lizan** [comment]
Where is 2e6796a cherry-picked from? Can you add PR number or original git sha to the commit message?

**Comment by lambdai** [comment]
ping @lizan @PiotrSikora  I updated in the description

**Review by lizan — APPROVED** [review]

**Pull request merged**
