### PR TITLE
[release-1.8] sync envoy release/v1.16

### PR DESCRIPTION
**Pull request by lambdai**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by bianpengyuan — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@howardjohn could you merge this (not squash) once the CI passes? We need to find a better way to do this, though, since most of those commits are already merged, but squashed in the previous sync commit (#294).

**Comment by howardjohn** [comment]
@PiotrSikora if we want to try it out just remove the hold

**Comment by PiotrSikora** [comment]
Thanks!

**Comment by PiotrSikora** [comment]
History retained, perfect!

**Pull request merged**
