### PR TITLE
Upgrade gRPC to 1.25 which has gRPC STS feature

### PR DESCRIPTION
**Pull request by JimmyCYJ**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Upgrade gRPC to [d8f4928fa779f6005a7fe55a176bdb373b0f910f](https://github.com/grpc/grpc/commit/d8f4928fa779f6005a7fe55a176bdb373b0f910f) (1.25.x).
Follow https://github.com/envoyproxy/envoy/pull/9041 that updates gRPC from 1.22 to 1.25.
Follow https://github.com/envoyproxy/envoy/issues/6584 that fixes compile issues complained by clang-8.

Description:
Risk Level: Low
Testing: Existing Tests
Docs Changes: N/A
Release Notes: N/A

https://github.com/istio/istio/issues/20133

### CODE REVIEW

**Comment by JimmyCYJ** [comment]
Got a compile issue

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/usr/local/go/src/istio.io/istio-envoy/envoy/tools/bazel.rc
INFO: Writing tracer profile to '/usr/local/.cache/bazel/_bazel/692781258b79ccbcfe64aa8d9ce81e87/command.profile.gz'
INFO: Analyzed target //source/exe:envoy-static (4 packages loaded, 1489 targets configured).
INFO: Found 1 target...
ERROR: /usr/local//go/src/istio.io/istio-envoy/envoy/source/common/http/BUILD:11:1: C++ compilation of rule '//source/common/http:async_client_lib' failed (Exit 1) clang failed: error executing command /bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 347 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
source/common/http/async_client_impl.cc:20:73: error: call to implicitly-deleted default constructor of 'const AsyncStreamImpl::NullRetryPolicy'
const AsyncStreamImpl::NullRetryPolicy AsyncStreamImpl::RouteEntryImpl::retry_policy_;
                                                                        ^
bazel-out/k8-opt/bin/source/common/http/_virtual_includes/async_client_lib/common/http/async_client_impl.h:147:33: note: default constructor of 'NullRetryPolicy' is implicitly deleted because field 'retriable_status_codes_' of const-qualified type 'const std::vector<uint32_t>' (aka 'const vector<unsigned int>') would not be initialized
    const std::vector<uint32_t> retriable_status_codes_;
                                ^
1 error generated.
Target //source/exe:envoy-static failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 143.211s, Critical Path: 29.15s
INFO: 62 processes: 62 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by PiotrSikora** [comment]
cc @istio/release-managers-1-4

**Comment by JimmyCYJ** [comment]
> shouldn't there be an Envoy upstream PR that applies your patch and is cherry picked back here? otherwise we would be maintaining a diverging branch. This applies even more so to master and 1.5 branch but I think is relevant here as well

I will update envoy upstream in a separate PR today or tomorrow, and upgrade gRPC SHA to the same SHA as this PR.
Envoy upstream and istio/envoy 1.5 branch both use gRPC 1.25.0, only 1.4 requires upgrading gRPC from 1.22 to 1.25. All the changes to other files are to fix build issues caused by upgrading from 1.22 to 1.25. envoy upstream master and istio/envoy 1.5 branch do not need those changes. I think the risk of diverge is low.

**Comment by howardjohn** [comment]
Ok I think this makes sense, but I would like approval from a proxy owner before merging

**Comment by JimmyCYJ** [comment]
> Ok I think this makes sense, but I would like approval from a proxy owner before merging

Thanks a lot!

**Comment by PiotrSikora** [comment]
Two comments:
1) Why do we need this in 1.4? We've made a decision long time ago that old branches are only for serious bug fixes and CVEs. This looks like a new feature?
2) In theory, we already switched to [Stable releases of Envoy](https://docs.google.com/document/d/1dFYR1b_n6Qz0caZmMqm008CKG7Q5eM5pXWPu0pAtGmw/edit) and [Istio Proxy switch to unmodified Envoy](https://docs.google.com/document/d/1M6uqZw2Zrcixic7wQM-9jJ4qaQIE3OvSfHSfkH6r9kQ/edit) (this is not strictly true, since we still maintain this repo, but we should move away from it), which means that this change should be suggested against Envoy v1.12 stable branch and we should get it from there.

**Comment by PiotrSikora** [comment]
Merging, because but I still think it's a bad idea...

**Pull request merged**
