### PR TITLE
Add upstream and downstream info in parent read callbacks in tcp too(#9949)

### PR DESCRIPTION
**Pull request by gargnupur**
Signed-off-by: gargnupur <gargnupur@google.com>
Ref: https://github.com/istio/istio/issues/20802

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description: git cherry-pick fade668c7edfbade082b40df1c6b9924bc7a7e0e
Upstream envoy PR: https://github.com/envoyproxy/envoy/pull/9949
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

12 lines of non-test code changes.

Rest is test.

### CODE REVIEW

**Comment by howardjohn** [comment]
@istio/release-managers-1-5 seems you are not owners here

**Comment by howardjohn** [comment]
is this in master?

**Comment by gargnupur** [comment]
@howardjohn : No, release 1.5 because that's what proxy/release 1.5 is based of

**Comment by gargnupur** [comment]
Envoy builds successfully (bazel build //source/exe:envoy-static)...

**Pull request merged**
