### PR TITLE
Backport of nack on fill fix.

### PR DESCRIPTION
**Pull request by jplevyak**

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]

**Comment by jwendell** [comment]
@jplevyak Is this fix worthy to mention on release notes for 1.7.1? Can you write a brief sentence explaining what bug was fixed - preferably with a link to an issue?

**Comment by JimmyCYJ** [comment]
> @jplevyak Is this fix worthy to mention on release notes for 1.7.1? Can you write a brief sentence explaining what bug was fixed - preferably with a link to an issue?

Friendly ping? This would help us collecting release notes for 1.7.1

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
@jplevyak is this a legit failure? It failed 3 times in a row

**Pull request merged**
