### PR TITLE
Revert STS changes from 1.4 branch

### PR DESCRIPTION
**Pull request by duderino**
This reverts all STS changes except for e0ecba310eba7c765ca36eb6519e0e48a3e73879 which I'm still figuring out how to handle.  Will address that in a subsequent PR.

### CODE REVIEW

**Comment by duderino** [comment]
And I think reverting https://github.com/istio/envoy/commit/e0ecba310eba7c765ca36eb6519e0e48a3e73879 is actually unnecessary.   It seems to be a merge of the prior commit from jplev and I manually verified that reverting the prior commit removed all of the changes in https://github.com/istio/envoy/commit/e0ecba310eba7c765ca36eb6519e0e48a3e73879 from the branch

**Comment by duderino** [comment]
@JimmyCYJ @kyessenov @bianpengyuan @jplevyak heads up, we (@mandarjog @howardjohn and @PiotrSikora) want to remove all STS changes from OSS Istio and keep them Google internal (we don't care that OSS sees them, but we think they are too much code to be introduced into an OSS patch release).   So I reverting all STS commits made by you in this PR.

Once this is merged we will cherry pick in the commits from today's 1.4.6 security release.

I'll also do something similar for the istio/proxy repo.

**Comment by kyessenov** [comment]
Heads up that some changes are actually bug fixes (e.g. gRPC metadata is not working in 1.4).

**Comment by bianpengyuan** [comment]
This file contains a fix for CreatingInitialMetadata (I should have separated it into a difference PR, but anyway..) I can send a PR with only that fix after this reverting is merged.

**Comment by duderino** [comment]
@bianpengyuan @kyessenov none of the commits I reverted were shipped in OSS Istio 1.4.6, so if you want them to go out in 1.4.7, please readd them later.

Once this is merged, then we want to cherrypick in the security fixes, tag it 1.4.6, and then you can send your PRs

**Comment by duderino** [comment]
@PiotrSikora looks like the wasm stress test is still present in this branch and its complaining.  I find that a bit surprising because it should be passing now that I've effectively rolled the branch back in time, but I could also just remove the stress test anyways.  Thoughts?

**Comment by duderino** [comment]
I get it, I have reverted commits to effectively bring us back to https://github.com/istio/envoy/pull/133 ... which was before istio/envoy ran automated tests.  So I shouldn't expect these tests to pass ;)

**Pull request closed without merging**
