### PR TITLE
Fixes ASSERT failure and infinite loop when attempting to unset readDisable state on a closed connection

### PR DESCRIPTION
**Pull request by dmitri-d**
Port of envoyproxy/envoy#9509

ping @lambdai

### CODE REVIEW

**Comment by dmitri-d** [comment]
@googlebot I fixed it

**Comment by dmitri-d** [comment]
@googlebot I fixed it.

**Comment by lambdai** [comment]
@dmitri-d Thanks for the backport!
The commit LGTM
The only thing is that the branch is not the best place 
CC release manager @jwendell @howardjohn

**Comment by howardjohn** [comment]
It should go to release-1.4 branch

And I guess also release-1.5?

**Comment by howardjohn** [comment]
Wow I can change it myself. nice

**Comment by dmitri-d** [comment]
* fixed test failure

**Comment by dmitri-d** [comment]
1.5 branch doesn't need this port -- the fix is there already (https://github.com/istio/envoy/commit/9de60274e1de35b9393375b27d32f40cd3c3e8ee).

**Pull request merged**
