### PR TITLE
Disable building Envoy filter example in CI

### PR DESCRIPTION
**Pull request by tbarrella**
See https://github.com/istio/istio/issues/30484

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]

**Review by bianpengyuan — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@tbarrella do you intent to target this to master branch and then cherry-pick this to release branches later?

**Comment by tbarrella** [comment]
I think so since it's failing in both 1.7 and 1.8 (do we have an automated way of creating cherry picks for this repo?)

**Comment by bianpengyuan** [comment]
I don't think auto cherry-pick is set up for this repo. We don't really use master branch of this repo so I think it is fine to just make the change to release branches.

**Comment by tbarrella** [comment]
Opened https://github.com/istio/envoy/pull/296 and https://github.com/istio/envoy/pull/297

**Comment by PiotrSikora** [comment]
Yeah, `master` branch is not even kept up to date in this repo, please only use release branches.

Could you also send this cherry-pick for 1.9?

**Pull request closed without merging**
