### PR TITLE
Set release managers as CODEOWNERS for release-1.7

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by PiotrSikora** [comment]
ASan is consistently failing in `//test/extensions/filters/udp/dns_filter:dns_filter_integration_test`.

@lizan @rshriram any ideas?

**Comment by dmitri-d** [comment]
At a quick glance the ASAN test failure in dns_filter_integration_test is in libc++. FWIW, all *SAN tests should be used with appropriately instumented libc, but that will increase CI memory usage.

**Comment by dmitri-d** [comment]
It appears that the 1.7 branch is missing the recent CI-related fixes for tsan tests (https://github.com/envoyproxy/envoy/pull/12134), which should at least resolve tsan flakes (vhds_integration_test is one).

**Comment by jwendell** [comment]
I have cherry-picked that PR into 1.7, let's see if that fixes the issues: https://github.com/istio/envoy/pull/241

**Comment by PiotrSikora** [comment]
It's ASan that's failing here, so TSan fix won't fix it.

**Comment by jwendell** [comment]
that's right. I closed it.

**Review by lizan — APPROVED** [review]

**Pull request merged**
