### PR TITLE
Sync with Envoy 1.16.1 to bring in two security fixes.

### PR DESCRIPTION
**Pull request by bianpengyuan**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@PiotrSikora Not sure if I did this correctly. I simply did a `git merge`. Is that right?

**Comment by bianpengyuan** [comment]
@PiotrSikora Also do you have permission to do a manual merge?

**Review by PiotrSikora — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@bianpengyuan yeah, `git merge`. I'm not sure if I have the correct permissions, let's re-check after tests pass.

Added `do-not-merge/work-in-progress` to prevent bot from merging and squashing this.

**Comment by PiotrSikora** [comment]
Looks that I don't have permission to merge this.

@duderino @howardjohn does either one of you have? If so, please merge this using "Create a merge commit" option.

**Pull request merged**
