### PR TITLE
1.4.6 security fixes

### PR DESCRIPTION
**Pull request by duderino**
This is just the release-1.4 branch from the private repo pushed to my git repo and turned into a PR against the public release-1.4 branch.  So there's no chance I missed anything ;)

### CODE REVIEW

**Comment by duderino** [comment]
@PiotrSikora what's the concern?  squashing?  Or you just want me to feel the burn?

**Comment by PiotrSikora** [comment]
Both.

**Comment by duderino** [comment]
I can't imagine a concern about squashing being bad, but I concur that I must feel the burn.  Will break it up (but want to see tests pass first since they take so long)

**Comment by PiotrSikora** [comment]
That's fine, you can do the "merge commit" once all tests pass. Squashing is "bad", because then it's hard to figure out which fixes are merged and which aren't from the history.

**Comment by duderino** [comment]
I was kidding about not understanding squashing being bad ;) I'll break these up

**Pull request merged**
