### PR TITLE
Cherrypick 647aea1 from envoyproxy/envoy

### PR DESCRIPTION
**Pull request by nrjpoddar**
Addresses: https://github.com/istio/istio/issues/17383 https://github.com/istio/istio/issues/17139

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@howardjohn @rlenglet are there no CI integrations for this repo?

**Comment by mandarjog** [comment]
Is this a cherry pick?

**Comment by nrjpoddar** [comment]
Yes cherry-pick of 647aea1 from envoyproxy/envoy to get stable serialization for Protobuf.Any

**Comment by kyessenov** [comment]
Ping @JimmyCYJ -- this fixes SDS, too, I think.

**Comment by kyessenov** [comment]
This doesn't look like a clean cherry-pick. Did you amend the commit?

**Comment by nrjpoddar** [comment]
> This doesn't look like a clean cherry-pick. Did you amend the commit?

Yes, there was a conflict in header includes:

```c++
#include "envoy/config/grpc_credential/v2alpha/file_based_metadata.pb.h"

#include "common/common/base64.h"
```

**Comment by nrjpoddar** [comment]
> Ping @JimmyCYJ -- this fixes SDS, too, I think.

@JimmyCYJ what SDS issue are we talking about here?

@kyessenov can I get a lgtm?

**Comment by nrjpoddar** [comment]
@rlenglet can this merged now?

**Comment by rlenglet** [comment]
No, 1.3.2 hasn't been released. I'll merge this after we do some cleanup post-1.3.2.

**Comment by rlenglet** [comment]
@nrjpoddar Please add an item for this PR into the [1.3.3 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.3-Draft).

**Pull request merged**
