### PR TITLE
Add Connection ID as property token (#583)

### PR DESCRIPTION
**Pull request by bianpengyuan**
Signed-off-by: gargnupur <gargnupur@google.com>

Signed-off-by: Nupur Garg <37600866+gargnupur@users.noreply.github.com>

Attempt to cherry-pick into v1.15 but miss the cut: https://github.com/envoyproxy/envoy-wasm/pull/585. So cherry-pick it directly here.

fyi @gargnupur 

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by bianpengyuan** [comment]
@istio/release-managers-1-7 The original PR has already been approved: envoyproxy/envoy-wasm#585 please take a look. Thanks!

**Comment by jwendell** [comment]
> /retest

@bianpengyuan tests are failing, see https://github.com/istio/istio/issues/25752

**Comment by jwendell** [comment]
Closing as this change was merged in https://github.com/istio/envoy/pull/242

**Pull request closed without merging**
