### PR TITLE
update opencensus

### PR DESCRIPTION
**Pull request by bianpengyuan**
Signed-off-by: Pengyuan Bian <bianpengyuan@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by mandarjog** [comment]
Is this a manual cherry-pick from main ?

**Comment by bianpengyuan** [comment]
Yes https://github.com/envoyproxy/envoy/pull/13549  will need to enable test on this branch.

**Comment by bianpengyuan** [comment]
@mandarjog ptal thanks!

**Comment by bianpengyuan** [comment]
@kyessenov @gargnupur ptal thanks!

**Review by kyessenov — APPROVED** [review]

**Pull request merged**
