### PR TITLE
wasm: fix network leak (#13836)

### PR DESCRIPTION
**Pull request by bianpengyuan**
Signed-off-by: Kuat Yessenov <kuat@google.com>

Signed-off-by: Kuat <kyessenov@users.noreply.github.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by bianpengyuan** [comment]
https://github.com/istio/istio/issues/24720

**Review by jwendell — APPROVED** [review]

**Review by JimmyCYJ — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@PiotrSikora @kyessenov Do you know if `//test/integration:tcp_proxy_integration_test` is a known flake? It failed 100% in CI but I cannot imagine how this PR could cause it...

Please advice since we hope to get this in as soon as possible in order to catch 1.7.7.

**Comment by PiotrSikora** [comment]
It's a flake, give it a few more tries. It's unrelated to this PR.

**Comment by bianpengyuan** [comment]
I probably will just disable the test for now when testing with tsan. There is no meaning to keep retrying a 100% failing flaky test.

**Comment by bianpengyuan** [comment]
Ok great.. now it fails because of a different reason:
```
ERROR: Analysis of target '//:envoy_binary_test' failed; build aborted: Analysis of target '@envoy//bazel/foreign_cc:zlib' failed
INFO: Elapsed time: 15.665s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (376 packages loaded, 2575 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (376 packages loaded, 2575 targets configured)
./ci/do_ci.sh: line 32: pushd: bazel-testlogs: No such file or directory
```

Looks like a non-retryable failure.. Will retry it one more time, if it still fails, we should make tsan non-required and debug it afterwards.

**Comment by kyessenov** [comment]
You could add flaky_test_attempts if it's really bad. Some tests are flakey even without Tsan.

**Comment by bianpengyuan** [comment]
https://github.com/istio/test-infra/pull/3160

**Pull request merged**
