### PR TITLE
Cherry-pick filter state PRs needed for TCP telemetry

### PR DESCRIPTION
**Pull request by kyessenov**
cc @gargnupur

### CODE REVIEW

**Comment by kyessenov** [comment]
Some commit is missing:
```
source/extensions/common/wasm/context.cc:1016:29: error: no member named 'setData' in 'std::shared_ptr<Envoy::StreamInfo::FilterState>'; did you mean to use '->' instead of '.'?
  stream_info->filterState().setData(key, std::make_unique<WasmState>(serialized_value),
```

**Comment by gargnupur** [comment]
Thanks @kyessenov

**Comment by kyessenov** [comment]
@jplevyak Can you confirm that the last commit is all I need to do to Wasm bits to make it work?

**Comment by kyessenov** [comment]
```
Target //source/exe:envoy-static up-to-date:
  bazel-bin/source/exe/envoy-static
INFO: Elapsed time: 47.512s, Critical Path: 46.92s
INFO: 27 processes: 27 linux-sandbox.
INFO: Build completed successfully, 30 total actions
```

**Pull request merged**
