### PR TITLE
Use sts for call credential when STS_PORT is provided in node metadata

### PR DESCRIPTION
**Pull request by bianpengyuan**
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by kyessenov** [comment]
Please comment with the associated PR/commit from master branch.

**Comment by bianpengyuan** [comment]
Corresponding PR to enable sts for tracing: https://github.com/envoyproxy/envoy/pull/9877

**Comment by kyessenov** [comment]
The PR in upstream envoy is different from this one. Should we try to pick the upstream change instead? We'd have to migrate to that anyways at some point.

**Comment by bianpengyuan** [comment]
I thought you mentioned it is not right to make API change to release branch? :) That is why I am doing one time hack for release-1.5 like the proxy filter. I think it is fine to leave 1.5 in this way. These options are not going to expose to user anyway, they are going to be hard coded by pilot-agent in 1.6. So I am not concerning about compatibility.

**Comment by kyessenov** [comment]
Oh OK, thanks for reminding. Yes, making xDS API change is hard since we'd have to upgrade all proto definitions. Good to keep this on the record when the time comes to 1.6.

**Pull request merged**
