### PR TITLE
Sync istio/envoy release-1.10 branch with 1.18.2 commit

### PR DESCRIPTION
**Pull request by Monkeyanator**
Syncs release-1.10 branch with Envoy commit `d362e791eb9e4efa8d87f6d878740e72dc8330ac` (SHA found in update PR [here](https://github.com/istio/proxy/pull/3294/files))

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]

**Comment by Monkeyanator** [comment]
@lizan think we need another approval on this when you have the chance

**Review by lambdai — APPROVED** [review]

**Review by jacob-delgado — APPROVED** [review]

**Comment by lizan** [comment]
Why do we need this? In last Networking WG meeting (see [notes](https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#heading=h.blfc5b8mxdcf)) we agreed that:
> istio/envoy fork is not needed, we can do the backports in envoyproxy (Istio maintainers are envoy maintainers). istio/proxy points to envoyproxy/envoy.

And now @dmitri-d is the stable maintainer in Envoy for Q2 2021.

**Pull request merged**
